### ISSUE TITLE
Exact match when query for event time

### ISSUE THREAD

**Issue by jkanner** [gwpy/gwosc#73]
In the latest version of the client, there is an error thrown when trying to get the GPS time of GW190521

```
from gwosc import datasets
t0 = datasets.event_gps('GW190521')
```

The error message says that the query for this event name gets multiple events (e.g. includes GW190521_074343).  This is not a great behavior, because I really want the GPS time of 'GW190521'.  I think when asking for a GPS time, it would be best to demand an exact match in the name (not a substring).

This seems to be a change from version 0.5.8 to 0.6.0.

**Comment by duncanmmacleod** [comment]
Gah, #67 was put in to specifically allow event data discovery for events where there is only a single event on that day, but it does have a HHMMSS suffix. I'll work up a patch and put out 0.6.1.
